name: Build

on:
  push:
    branches: [ patch-1 ]
  pull_request:
    branches: [ patch-1 ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: patch-1
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: |
        for s in restore.sh build.sh
        do bash "${s}"
        done && git status &&
        git add src/Compilers/CSharp/Portable/xlf/CSharpResources.*.xlf &&
        git commit -m 'CSharpResources: translation base update' &&
        git push
